[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/checkout"
  to = "/checkout.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/client.html"
  status = 200

[functions]
  node_bundle = true
